# This is a basic workflow to help you get started with Actions

name: Bootcamp 2020 urdu

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Setup Node.js environment
      - uses: actions/setup-checkout@v14.15.5.
      
        with:
          node-version: 12

      # Runs a set of commands using the runners shell
      - name: Installing surge
      - uses: npm install --global surge@v0.21.7
      
      - name: deploying using surge
      - uses: surge ./ long-volcano.surge.sh --token ${{ secrets.SURGE_TOKEN }}
